### ISSUE TITLE
install

### ISSUE THREAD

**Issue by jacobeisenstein** [simonccarter/sta#1]
Nice code. I had to do two things to install
1. To get autogen.sh to work:
   ln -s makefile.am Makefile.am 
2. To get it to compile, I had to change #include <string> to #include <string.h> in sta.cpp. 

I think issue #2 has something to do with my linux/gcc config.

**Comment by sfd99** [comment]
**_Hi Simon,_**

 **In Ubuntu Linux 20.04.4, (LTS 64 bits)
w/ R 4.0.2**

**Installing sta**
Run ./autogen.sh, ./configure, make, and make install.

So, I tried to follow the Install instructions 
but get:

~/Science/Math/STATS/STA$ sh ./autogen.sh
**sh: 0: Can't open ./autogen.sh**

or also:
~/Science/Math/STATS/STA$ ./autogen.sh
**bash: ./autogen.sh: No such file or directory**

**_btw:_**
  autogen.sh IS already _excutable_ in the Permissions.

Sorry, I'm not good at compiling progs in C.
Can you help with baby step instructions
for installing STA in Ubuntu Linux?.

Thanks, 
really eager to try STA out!.

SFd99
San Francisco
